export const STACK = [
	{
		name: "Typescript",
		logo: "typescript.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "Javascript",
		logo: "javascript.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "Python",
		logo: "python.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "PHP",
		logo: "php.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "HTML",
		logo: "html.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "CSS",
		logo: "css.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "NodeJS",
		logo: "nodejs.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "Tailwind CSS",
		logo: "tailwind.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "Bootstrap",
		logo: "bootstrap.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "React",
		logo: "react.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "CodeIgniter 4",
		logo: "ci4.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "NextJS",
		logo: "nextjs.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "Flask",
		logo: "flask.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "ExpressJS",
		logo: "expressjs.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "Docker",
		logo: "docker.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "GitHub",
		logo: "github.png",
		href: "https://github.com/ranas0n",
		hoverColor: "hover:bg-pastel-pink",
		category: "using",
	},
	{
		name: "MySQL",
		logo: "mysql.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "PostgreSQL",
		logo: "postgresql.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "MongoDB",
		logo: "mongodb.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
	{
		name: "Tensorflow",
		logo: "tensorflow.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "using",
	},
	{
		name: "Pytorch",
		logo: "pytorch.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
		category: "learning",
	},
];
